---
- name: Add new customers to Palo Alto Panorama
  hosts: panorama
  connection: local
  gather_facts: no

  tasks:
    - name: Add new customer entries to Panorama
      panos_address_object:
        provider:
          ip_address: "{{ panorama_ip }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        name: "{{ item.ObjectName }}"
        value: "{{ item.CustomerIPAddress }}/{{ item.IPSubnetMask }}"
        description: "Customer Entry for {{ item.CustomerName }}"
        tag: "{{ item.Tags }}"
      with_items: "{{ customers }}"
