- name: Push Customer Configurations to Panorama
  hosts: panorama
  connection: local
  gather_facts: no

  vars_files:
    - panorama_credentials.yml

  tasks:
    - name: Load customer YAML file
      include_vars:
        file: "{{ customer_file }}"
      register: customer_data

    - name: Configure objects in Panorama
      panos_object:
        provider:
          ip_address: "{{ panorama_credentials.ip_address }}"
          username: "{{ panorama_credentials.username }}"
          password: "{{ panorama_credentials.password }}"
        object_type: "address"
        name: "{{ item.ObjectName }}"
        value: "{{ item.CustomerIPAddress }}/{{ item.IPSubnetMask }}"
        tags: "{{ item.Tags }}"
      loop: "{{ customer_data.customers }}"

    - name: Commit configuration in Panorama
      panos_commit:
        provider:
          ip_address: "{{ panorama_credentials.ip_address }}"
          username: "{{ panorama_credentials.username }}"
          password: "{{ panorama_credentials.password }}"

    - name: Push configuration to Firewall
      panos_push:
        provider:
          ip_address: "{{ panorama_credentials.ip_address }}"
          username: "{{ panorama_credentials.username }}"
          password: "{{ panorama_credentials.password }}"
        devicegroup: "{{ firewall_devicegroup }}"
