- name: Push Customer Configurations to Panorama
  hosts: panorama
  connection: local
  gather_facts: no

  vars:
    customer_file: "customers.yml"  # Path to the generated customer YAML file

  tasks:
    - name: Load customer YAML file
      include_vars:
        file: "{{ customer_file }}"
      register: customer_data

    - name: Configure objects in Panorama
      panos_object:
        provider:
          ip_address: "{{ panorama_ip }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        object_type: "address"
        name: "{{ item.ObjectName }}"
        value: "{{ item.CustomerIPAddress }}/{{ item.IPSubnetMask }}"
        tags: "{{ item.Tags }}"
      loop: "{{ customer_data.customers }}"

    - name: Commit configuration in Panorama
      panos_commit:
        provider:
          ip_address: "{{ panorama_ip }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"

    - name: Push configuration to Firewall
      panos_push:
        provider:
          ip_address: "{{ panorama_ip }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        devicegroup: "{{ firewall_devicegroup }}"
